<a href="https://colab.research.google.com/github/nethajisubash/nlp/blob/main/FoodReview.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1 align='center'>Python Regular Expression Tutorial Exericse</h1>

In [1]:
import numpy as np
import pandas as pd
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding


In [3]:
reviews =  ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
          'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [7]:
one_hot('amazing restaurant',30)

[10, 2]

In [9]:
vocab_size = 30
encoded_reviews = [one_hot(d,vocab_size) for d in reviews]
print(encoded_reviews)

[[20, 2], [10, 2], [26, 14], [11, 4, 17], [23, 13, 18], [21, 2], [28, 13, 25], [6, 23], [6, 19], [2, 13]]


In [11]:
#padding based on sentence length
sentence_length = 3
padded_reviews = pad_sequences(encoded_reviews, maxlen=sentence_length, padding='post')
print(padded_reviews)

[[20  2  0]
 [10  2  0]
 [26 14  0]
 [11  4 17]
 [23 13 18]
 [21  2  0]
 [28 13 25]
 [ 6 23  0]
 [ 6 19  0]
 [ 2 13  0]]


In [12]:
embedding_vector_length = 4
model = Sequential()
model.add(Embedding(vocab_size, embedding_vector_length, input_length=sentence_length, name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))


In [13]:
X_train = padded_reviews
y_train = sentiment

In [14]:
model.compile('adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 4)              120       
                                                                 
 flatten (Flatten)           (None, 12)                0         
                                                                 
 dense (Dense)               (None, 1)                 13        
                                                                 
Total params: 133 (532.00 Byte)
Trainable params: 133 (532.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [15]:
model.fit(X_train, y_train, epochs=50, verbose=0)

In [16]:
loss, accuracy = model.evaluate(X_train, y_train, verbose=0)
print('Accuracy: %f' % (accuracy*100))

Accuracy: 100.000000


In [17]:
model.get_layer('embedding').get_weights()[0]

array([[ 0.09501718,  0.08926638,  0.08646975,  0.0999371 ],
       [ 0.01932937,  0.02862961, -0.01201664,  0.03246267],
       [-0.05045304,  0.00813955, -0.08474198,  0.03488208],
       [ 0.02385242, -0.03065398, -0.04793371, -0.00778081],
       [-0.01132744, -0.00843562, -0.0277553 ,  0.01687733],
       [ 0.04630834, -0.01935979,  0.04174657, -0.00641043],
       [-0.06640022,  0.03746063, -0.04908629,  0.01933245],
       [ 0.04126288, -0.0090788 ,  0.00605805, -0.01275263],
       [-0.03653526, -0.02166001,  0.04103707, -0.04599842],
       [ 0.01007265,  0.03163227,  0.00710315, -0.00986067],
       [ 0.00384662, -0.06987723,  0.04373436, -0.0172582 ],
       [ 0.00096309, -0.03248653,  0.08506902, -0.06372762],
       [-0.01861669, -0.04767466, -0.0247542 ,  0.0327641 ],
       [ 0.00739183,  0.09706657,  0.05758524, -0.04054089],
       [ 0.00116396, -0.04429734, -0.09347602,  0.09833968],
       [ 0.00170221, -0.00442885,  0.00969952,  0.04918456],
       [-0.01130397, -0.