<a href="https://colab.research.google.com/github/nethajisubash/nlp/blob/main/Word2Vec.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1 align='center'>Python Regular Expression Tutorial Exericse</h1>

In [1]:
import numpy as np
import pandas as pd
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding


In [3]:
reviews =  ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
          'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [7]:
one_hot('amazing restaurant',30)

[10, 2]

In [32]:
vocab_size = 50
encoded_reviews = [one_hot(d,vocab_size) for d in reviews]
print(encoded_reviews)

[[12, 37], [40, 17], [30, 34], [47, 2, 25], [3, 4, 9], [36, 37], [35, 4, 15], [37, 14], [37, 12], [14, 12]]


In [19]:
#padding based on sentence length
sentence_length = 3
padded_reviews = pad_sequences(encoded_reviews, maxlen=sentence_length, padding='post')
print(padded_reviews)

[[12 37  0]
 [40 17  0]
 [30 34  0]
 [47  2 25]
 [ 3  4  9]
 [36 37  0]
 [35  4 15]
 [37 14  0]
 [37 12  0]
 [14 12  0]]


In [20]:
embedding_vector_length = 4
model = Sequential()
model.add(Embedding(vocab_size, embedding_vector_length, input_length=sentence_length, name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))


In [21]:
X_train = padded_reviews
y_train = sentiment

In [22]:
model.compile('adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 4)              200       
                                                                 
 flatten_1 (Flatten)         (None, 12)                0         
                                                                 
 dense_1 (Dense)             (None, 1)                 13        
                                                                 
Total params: 213 (852.00 Byte)
Trainable params: 213 (852.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [23]:
model.fit(X_train, y_train, epochs=50, verbose=0)

In [24]:
loss, accuracy = model.evaluate(X_train, y_train, verbose=0)
print('Accuracy: %f' % (accuracy*100))

Accuracy: 100.000000


In [27]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

50

In [30]:
weights[12]

array([ 0.0296828 , -0.04602828,  0.04741298, -0.07616761], dtype=float32)

In [33]:
weights[40]

array([ 0.02093482,  0.08320901,  0.06603934, -0.05446577], dtype=float32)

In [ ]:
#checking on nice (12) and amazing(40) is close enough vector. Cosine matching.
#you can save teh wegiths based on the traning and use it later.